### ISSUE TITLE
pinpoint code example shows a blank plot in Rstudio Viewer [SOLVED!]

### ISSUE THREAD

**Issue by sfd99** [daranzolin/pinpoint#3]
**_Hi David,_**

the pinpoint pkg is a great idea!.

The pinpoint code example in the Github page,
runs ok (no error messages),
but it **_shows a blank plot in Rstudio Viewer_**
...no plot at all, 
- just a 100% blank Viewer space.

**_Git page example code:_**
> mtcars %>% 
     pinpoint(x = mpg, 
              fill = cyl, 
              tooltip = name,
              compare_to = "diff_from_mean",
              title = "MPG by Cylinder") %>% 
     pp_style(jitter_width = 60,
              number_format = ".2")

HELP, David!,
 (I'd love to see pinpoint work!).

**SFer
San Francisco**
Rstudio 1.1.463 / R 3.6.1 / Ubuntu Linux 14.04 32bit
**_UPDATE:_**
ok - I got it...to see the resulting plot,
you have to click the icon button:
   **[Show in New Window]**
at the top of the Viewer pane in Rstudio.
Problem solved!. :-)

**Comment by daranzolin** [comment]
This is confusing to me as well. I had asked about it on the RStudio Community forums, but never got a response: https://community.rstudio.com/t/what-is-are-the-reason-s-an-htmlwidget-doesnt-render-in-the-rstudio-viewer-pane/35104

Besides the RStudio Viewer, I haven't had any other problems getting it to appear.
